development:
  adapter: postgresql
  encoding: unicode
  database: Xiaoxiong
  pool: 5
  username: Xiaoxiong
  password: xiaoxiong

test:
  adapter: postgresql
  encoding: unicode
  database: Xiaoxiong
  pool: 5
  username: Xiaoxiong
  password: xiaoxiong

production:
  adapter: postgresql
  encoding: unicode
  database: Xiaoxiong
  pool: 5
  username: Xiaoxiong
  password: xiaoxiong